#!/usr/bin/env bash

pjail="141amd64"
pbranch="quarterly"
pport="quarterly"
pproj="devel/root"

mkfile="/usr/local/poudriere/ports/${pport}/${pproj}/Makefile"
pdconf="/usr/local/etc/poudriere.d"
pddata="/usr/local/poudriere/data"
pdcmd="poudriere testport -b ${pbranch} -j ${pjail} -o ${pproj} -p ${pport} -vv"



if [[ $# -eq 0 ]] ; then
  echo "Testing with each individual port option (EMPTY implies all options disabled)."
  OPTS="EMPTY $(gawk '$1 == "OPTIONS_DEFINE=" {
                 for (i = 2; i <= NF; i++) {
                   if (i == NF) x=$i
                   else printf $i " "
                 }
                 while (x == "\\") {
                   getline
                   for (i = 1; i <= NF; i++) {
                     if (i == NF) x=$i
                     if ($i != "\\") printf $i " "
                   }
                 }
               }' $mkfile)"
elif [[ $1 = "default" ]] ; then
  _default=1
  echo "Testing with default port options (one go)."
else
  echo "Testing with each individual user-specified option."
  OPTS="$@"
fi

if [[ _default -eq 1 ]] ; then
  echo "Options: See OPTIONS_DEFAULT in $mkfile."
else
  echo "Options: $OPTS"
fi
sleep 5



if [[ _default -eq 1 ]] ; then
  sudo bash -c "${pdcmd}"
  exit 0
fi



for opt in $OPTS ; do
  identifier=$opt
  if [[ "$opt" = "EMPTY" ]] ; then
    opt=""
  fi

  # TODO: Use regular ${pjail}-${pport} as fetch url
  #  cfgfile="${pdconf}/${pjail}-${pport}-${identifier}-poudriere.conf"
  #  sudo rm -f $cfgfile ; sudo touch $cfgfile ; sudo chmod g+w $cfgfile
  #  sudo echo "PACKAGE_FETCH_URL=file://${pddata}/packages/${pjail}-${pport}" > $cfgfile

  optdir="${pdconf}/${pjail}-${pport}-${identifier}-options/${pproj/\//_}"
  optfile="${optdir}/options"
  sudo mkdir -p $optdir
  sudo rm -f $optfile ; sudo touch $optfile ; sudo chmod g+w $optfile

  for other_opt in $OPTS ; do
    if [ "$other_opt" == "$opt" ] ; then
      sudo echo "OPTIONS_FILE_SET+=$other_opt" >> $optdir/options
    else
      sudo echo "OPTIONS_FILE_UNSET+=$other_opt" >> $optdir/options
    fi
  done

  sudo bash -c "${pdcmd} -z $identifier"
done

exit 0